name: ci

on:
  pull_request:
    branches: [ develop, master ]

  push:
    branches:
      - develop

jobs:

  Tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13.3
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: password
          POSTGRES_DB: db_test
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Install dependecies
        uses: igp7/action-pipenv@v1.0.0
        with:
          command: install

      - name: Unit Tests
        uses: igp7/action-pipenv@v1.0.0
        with:
          command: run tests_unit
        env:
          DATABASE_TEST_URL: postgresql+psycopg2://root:password@postgres:5432/db_test

      - name: Integration Tests
        uses: igp7/action-pipenv@v1.0.0
        with:
          command: run tests_integration
        env:
          DATABASE_TEST_URL: postgresql+psycopg2://root:password@postgres:5432/db_test

      - name: API Tests
        uses: igp7/action-pipenv@v1.0.0
        with:
          command: run tests_api
        env:
          DATABASE_TEST_URL: postgresql+psycopg2://root:password@postgres:5432/db_test
